#!/bin/bash
set -euo pipefail

cd /home/container

# Pterodactyl/Wings runs the container with a numeric UID/GID that may not exist
# in the image's /etc/passwd. PostgreSQL initdb (and some other services) call
# getpwuid(), so provide a runtime NSS identity without modifying the read-only rootfs.
CURRENT_UID="$(id -u)"
CURRENT_GID="$(id -g)"

NSS_WRAPPER_LIB=""

# Prefer the dynamic linker cache; Debian/Ubuntu commonly installs the library
# in a multi-arch directory and libnss_wrapper.so may itself be a symlink.
if command -v ldconfig >/dev/null 2>&1; then
    NSS_WRAPPER_LIB="$(ldconfig -p 2>/dev/null | awk '/libnss_wrapper\.so/{print $NF; exit}' || true)"
fi

# Fallback: search common library roots. Do NOT restrict to -type f because the
# unversioned .so can be a symlink.
if [ -z "${NSS_WRAPPER_LIB}" ]; then
    NSS_WRAPPER_LIB="$(find /usr/lib /usr/lib64 /lib /lib64 \
        \( -name 'libnss_wrapper.so' -o -name 'libnss_wrapper.so.*' \) \
        2>/dev/null | head -n1 || true)"
fi

if [ -z "${NSS_WRAPPER_LIB}" ] || [ ! -e "${NSS_WRAPPER_LIB}" ]; then
    echo "ERROR: libnss_wrapper is not available in the image." >&2
    echo "Diagnostic library search:" >&2
    find /usr/lib /usr/lib64 /lib /lib64 -maxdepth 4 \
        -iname '*nss*wrapper*' -print 2>/dev/null >&2 || true
    exit 1
fi

echo "Using NSS wrapper: ${NSS_WRAPPER_LIB}"

mkdir -p /home/container/.nss

cat > /home/container/.nss/passwd <<EOF
container:x:${CURRENT_UID}:${CURRENT_GID}:Pterodactyl Container:/home/container:/bin/bash
EOF

cat > /home/container/.nss/group <<EOF
container:x:${CURRENT_GID}:
EOF

export NSS_WRAPPER_PASSWD=/home/container/.nss/passwd
export NSS_WRAPPER_GROUP=/home/container/.nss/group
export LD_PRELOAD="${NSS_WRAPPER_LIB}${LD_PRELOAD:+:${LD_PRELOAD}}"
export USER=container
export LOGNAME=container
export HOME=/home/container

echo "Pterodactyl runtime identity: UID=${CURRENT_UID} GID=${CURRENT_GID}"

PORT="${SERVER_PORT:?Pterodactyl did not provide SERVER_PORT}"
DOMAIN="${DOMAIN_NAME:-plane.example.com}"
PUBLIC_PROTOCOL="${APP_PROTOCOL:-https}"
UPLOAD_LIMIT="${FILE_SIZE_LIMIT:-104857600}"

mkdir -p \
    logs/access logs/error logs/backend logs/services \
    data data/static-assets .config .local/share \
    services/postgres/data services/postgres/run \
    services/redis \
    services/rabbitmq/data services/rabbitmq/log services/rabbitmq/home services/rabbitmq/plugins \
    services/minio/data/uploads

# Keep every secret generated by this Plane instance in the Pterodactyl server folder.
# Nothing sensitive is baked into the egg or Docker image.
SECRETS_FILE="/home/container/.plane-internal-secrets"
if [ ! -f "${SECRETS_FILE}" ]; then
    python3 - <<'PY' > "${SECRETS_FILE}"
import secrets
print("POSTGRES_PASSWORD=" + secrets.token_urlsafe(36))
print("REDIS_PASSWORD=" + secrets.token_urlsafe(36))
print("RABBITMQ_PASSWORD=" + secrets.token_urlsafe(36))
print("MINIO_ACCESS_KEY=plane" + secrets.token_hex(8))
print("MINIO_SECRET_KEY=" + secrets.token_urlsafe(40))
print("SECRET_KEY=" + secrets.token_hex(48))
print("LIVE_SERVER_SECRET_KEY=" + secrets.token_hex(48))
PY
    chmod 600 "${SECRETS_FILE}" || true
fi

set -a
# shellcheck disable=SC1090
source "${SECRETS_FILE}"
set +a

SERVICE_ENV="/home/container/.plane-service-env"
cat > "${SERVICE_ENV}" <<EOF
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
EOF
chmod 600 "${SERVICE_ENV}" || true

# Initialise PostgreSQL only once. PostgreSQL runs as Pterodactyl's non-root UID.
PG_BINDIR="$(pg_config --bindir 2>/dev/null || true)"
if [ -z "${PG_BINDIR}" ] || [ ! -x "${PG_BINDIR}/initdb" ]; then
    PG_BINDIR="$(dirname "$(find /usr/lib/postgresql /usr/local -type f -name initdb -perm -111 2>/dev/null | head -n1)")"
fi

if [ -z "${PG_BINDIR}" ] || [ ! -x "${PG_BINDIR}/initdb" ]; then
    echo "ERROR: PostgreSQL initdb binary was not found in the image." >&2
    exit 1
fi

printf '%s\n' "${PG_BINDIR}" > /home/container/services/postgres/bindir

if [ ! -s /home/container/services/postgres/data/PG_VERSION ]; then
    echo "Initialising embedded PostgreSQL..."
    PWFILE="$(mktemp)"
    printf '%s\n' "${POSTGRES_PASSWORD}" > "${PWFILE}"
    "${PG_BINDIR}/initdb" \
        -D /home/container/services/postgres/data \
        --username=plane \
        --pwfile="${PWFILE}" \
        --auth-local=trust \
        --auth-host=scram-sha-256 \
        --encoding=UTF8 \
        --no-locale
    rm -f "${PWFILE}"

    cat >> /home/container/services/postgres/data/postgresql.conf <<'EOF'
listen_addresses = '127.0.0.1'
port = 5432
max_connections = 1000
unix_socket_directories = '/home/container/services/postgres/run'
EOF

    # Create Plane's database before Supervisor starts the permanent PostgreSQL process.
    "${PG_BINDIR}/pg_ctl" \
        -D /home/container/services/postgres/data \
        -o "-c listen_addresses='' -c unix_socket_directories=/home/container/services/postgres/run" \
        -w start

    "${PG_BINDIR}/createdb" \
        -h /home/container/services/postgres/run \
        -U plane \
        plane

    "${PG_BINDIR}/pg_ctl" \
        -D /home/container/services/postgres/data \
        -m fast \
        -w stop
fi

# Ensure a clean writable socket directory every boot.
rm -f /home/container/services/postgres/run/.s.PGSQL.* 2>/dev/null || true
rm -f /home/container/services/postgres/data/postmaster.pid 2>/dev/null || true

if [ ! -f /home/container/plane.env ]; then
    cp /app/plane.env.template /home/container/plane.env
fi

set_env() {
    local key="$1"
    local value="$2"
    if grep -q "^${key}=" /home/container/plane.env; then
        sed -i "s|^${key}=.*|${key}=${value}|" /home/container/plane.env
    else
        printf '%s=%s\n' "${key}" "${value}" >> /home/container/plane.env
    fi
}

# All dependencies are loopback-only and live inside this same Pterodactyl container.
DATABASE_URL="postgresql://plane:${POSTGRES_PASSWORD}@127.0.0.1:5432/plane"
REDIS_URL="redis://:${REDIS_PASSWORD}@127.0.0.1:6379/0"
AMQP_URL="amqp://plane:${RABBITMQ_PASSWORD}@127.0.0.1:5672/plane"
AWS_S3_ENDPOINT_URL="http://127.0.0.1:9000"
PUBLIC_URL="${PUBLIC_PROTOCOL}://${DOMAIN}"

set_env DOMAIN_NAME "${DOMAIN}"
set_env APP_DOMAIN "${DOMAIN}"
set_env SITE_ADDRESS ":${PORT}"
set_env APP_PROTOCOL "${PUBLIC_PROTOCOL}"
set_env WEB_URL "${PUBLIC_URL}"
set_env CORS_ALLOWED_ORIGINS "${PUBLIC_URL}"
set_env API_BASE_URL "http://localhost:3004"

set_env DATABASE_URL "${DATABASE_URL}"
set_env REDIS_URL "${REDIS_URL}"
set_env AMQP_URL "${AMQP_URL}"

set_env USE_MINIO "1"
set_env AWS_REGION "us-east-1"
set_env AWS_ACCESS_KEY_ID "${MINIO_ACCESS_KEY}"
set_env AWS_SECRET_ACCESS_KEY "${MINIO_SECRET_KEY}"
set_env AWS_S3_ENDPOINT_URL "${AWS_S3_ENDPOINT_URL}"
set_env AWS_S3_BUCKET_NAME "uploads"
set_env BUCKET_NAME "uploads"
set_env MINIO_ENDPOINT_SSL "0"

set_env SECRET_KEY "${SECRET_KEY}"
set_env LIVE_SERVER_SECRET_KEY "${LIVE_SERVER_SECRET_KEY}"
set_env FILE_SIZE_LIMIT "${UPLOAD_LIMIT}"
set_env API_KEY_RATE_LIMIT "${API_KEY_RATE_LIMIT:-60/minute}"
set_env AUTHENTICATION_RATE_LIMIT "${AUTHENTICATION_RATE_LIMIT:-10/minute}"

export \
    DOMAIN_NAME="${DOMAIN}" \
    APP_DOMAIN="${DOMAIN}" \
    SITE_ADDRESS=":${PORT}" \
    APP_PROTOCOL="${PUBLIC_PROTOCOL}" \
    WEB_URL="${PUBLIC_URL}" \
    CORS_ALLOWED_ORIGINS="${PUBLIC_URL}" \
    API_BASE_URL="http://localhost:3004" \
    DATABASE_URL \
    REDIS_URL \
    AMQP_URL \
    USE_MINIO=1 \
    AWS_REGION=us-east-1 \
    AWS_ACCESS_KEY_ID="${MINIO_ACCESS_KEY}" \
    AWS_SECRET_ACCESS_KEY="${MINIO_SECRET_KEY}" \
    AWS_S3_ENDPOINT_URL \
    AWS_S3_BUCKET_NAME=uploads \
    BUCKET_NAME=uploads \
    MINIO_ENDPOINT_SSL=0 \
    SECRET_KEY \
    LIVE_SERVER_SECRET_KEY \
    FILE_SIZE_LIMIT="${UPLOAD_LIMIT}"

echo
echo "------------------------------------------------"
echo "Plane CE - Pterodactyl True All-In-One"
echo "------------------------------------------------"
echo "Public domain       : ${PUBLIC_URL}"
echo "Pterodactyl port    : ${PORT}"
echo "Plane proxy         : 127.0.0.1:${PORT}"
echo "PostgreSQL          : 127.0.0.1:5432 (embedded)"
echo "Redis               : 127.0.0.1:6379 (embedded)"
echo "RabbitMQ            : 127.0.0.1:5672 (embedded)"
echo "MinIO               : 127.0.0.1:9000 (embedded)"
echo "Public uploads      : ${PUBLIC_URL}/uploads/"
echo "USE_MINIO           : forced to 1 for Plane backend"
echo "Django static root  : /home/container/data/static-assets"
echo "Persistent root     : /home/container"
echo "Secrets             : auto-generated and persisted"
echo "------------------------------------------------"
echo

exec /app/start.sh
